spring.application.name=edutec

# Entorno de PayPal
paypal.api.base-url=${PAYPAL_BASE_URL:https://api-m.sandbox.paypal.com}

# Credenciales Inyectadas
paypal.client.id=${PAYPAL_CLIENT_ID}
paypal.client.secret=${PAYPAL_CLIENT_SECRET}